
export const operators = [
    { id: 2202, value: 'ac' },
    { id: 2201, value: 'cont' },
    { id: 1464, value: 'eq' },
    { id: 1466, value: 'gt' },
    { id: 1468, value: 'gte' },
    { id: 1467, value: 'lt' },
    { id: 1469, value: 'lte' },
    { id: 3011, value: 'notcontains' },
    { id: 1465, value: 'noteq' },
  ];
  export const functions = [
    { function_id: 291862, function_name: 'Board of Director Officer' },
    { function_id: 292049, function_name: 'Code of Ethics' },
    { function_id: 1256, function_name: 'Compliance / Regulatory' },
    { function_id: 291861, function_name: 'ESG' },
    { function_id: 1260, function_name: 'Executives' },
    { function_id: 292064, function_name: 'Finance' },
    { function_id: 1258, function_name: 'HR' },
    { function_id: 291866, function_name: 'Institutional Business' },
    { function_id: 1253, function_name: 'Investment' },
    { function_id: 1255, function_name: 'Investor Relations' },
    { function_id: 291889, function_name: 'IT' },
    { function_id: 1257, function_name: 'Legal' },
    { function_id: 1254, function_name: 'ODD / Operations' },
    { function_id: 1262, function_name: 'Others' },
    { function_id: 292022, function_name: 'PIM' },
    { function_id: 1292, function_name: 'Primary Owner' },
    { function_id: 292070, function_name: 'Product Governance' },
    { function_id: 1259, function_name: 'RiskManagement' },
    { function_id: 1293, function_name: 'Secondary Owner' },
    { function_id: 1261, function_name: 'Technology / CISO' },
    { function_id: 292071, function_name: "Treasurer's Office " },
  ];
  
  export const subscription_limits = [
    {
      id: 1,
      firm_id: 2,
      type_id: 'Fund',
      limit: 150,
      created_by: 1,
      created_at: '2017-04-17T13:48:07',
    },
  ];
  
  
  export const team_member = [
    {
      associated_firms_count: 0,
      recaptchaToken: null,
      signupVerificationCode: null,
      referral_data: null,
      is_default: false,
      userName: 'anamika.bhandari+investor@diligencevault.com',
      password: null,
      confirmPassword: null,
      newPassword: null,
      id: 93706,
      type: 'investor',
      firstName: 'Anamika',
      lastName: 'Investror',
      fullName: 'Anamika Investror',
      firmInfo: null,
      accessLevel: 'NA',
      accessLevelID: 0,
      isAdmin: false,
      isReadOnly: false,
      is_approver: false,
      active: false,
      country: null,
      avatarURL: null,
      title: null,
      psk: null,
      twoFactorEnabled: false,
      anonymous: false,
      bounced_at: null,
      phone: null,
      eucAccepted: false,
      group_by_intro: false,
      review_functionality_intro: false,
      discussEUCAccepted: false,
      isFirstLogin: true,
      firmAccessCount: 0,
      conversionDateTime: '2023-12-15T08:50:56',
      isFirstDD: true,
      isFirstTemplate: true,
      statusCode: 0,
      fundId: 0,
      lastTouchPoint: null,
      owner_user_id: null,
      owner_name: null,
      contact_type_ids: null,
      contact_types: null,
      type_ids: null,
      street_address_1: null,
      street_address_2: null,
      city: null,
      state: null,
      zipcode: null,
      country_id: 0,
      phone_1: null,
      phone_2: null,
      fax: null,
      relationship_status_id: 0,
      relationship_status: null,
      associated_funds: [],
      associated_programs: [],
      associated_strategies: [],
      lockoutEndDateUtc: null,
      key: null,
      firm_name: '',
      is_tracking: false,
      is_verified: false,
      is_owner: false,
      is_new_user: false,
      skip_tour: false,
      approved_by: null,
      approved_at: null,
      send_invitation: false,
      can_change_firm: false,
      last_updated_at: null,
      api_key: null,
      firmwide_role: null,
      firmwide_role_alias: null,
      firmwide_role_id: 0,
      is_saml_enabled: false,
      platform_active: false,
      relationship_active: false,
    },
  ];
  
  export const commonData = {
    subscription_limits,
    operators,
    functions,
    team_member,
  };
  


 