import { ALL_USER_ROLE } from "tests/types/user-role.type";
import { commonData } from "./common";

export const account = {
  associated_firms_count: 0,
  recaptchaToken: null,
  signupVerificationCode: null,
  referral_data: null,
  is_default: false,
  userName: 'investors@diligencevault.com',
  password: null,
  confirmPassword: null,
  newPassword: null,
  id: 320,
  type: 'investor',
  firstName: 'investor',
  lastName: 'account',
  fullName: 'investor account',
  firmInfo: {
    notification_contacts: [],
    id: 2,
    name: 'World Pensions test',
    firm_type_id: 0,
    firm_type: null,
    subscription: 'Productive',
    accessProfile: 0,
    website: null,
    inceptionDate: null,
    expiryDate: '2025-07-31T18:30:00',
    aum: 0.0,
    currency: null,
    currencyID: 0,
    contactPerson: null,
    contacts: null,
    firmDescription: null,
    isInvestor: false,
    isDocToHtmlEnabled: false,
    api_key: null,
    lastTouchPoint: null,
    owner_user_id: null,
    owner_name: null,
    relationship_status_id: null,
    relationship_status_name: null,
    active: false,
    admin_user_email: null,
    key: null,
    alternate_name: null,
    email_domain: null,
    is_tracking: false,
    preferences: {
      firm_id: 2,
      created_by: 2,
      created_at: '2017-01-23T13:41:05.18',
      include_system: true,
      include_system_rating: false,
      hide_employees: false,
      add_generic_email: false,
      generic_email: null,
      add_sender_email: false,
      sender_email: null,
      auto_reminder: false,
      customize_intro: false,
      introduction: null,
      include_disclosure: false,
      disclosure: 'This is disclosure from firm two',
      add_cc_email: false,
      cc_email: 'purvi@ifourtechnolab.com',
      bcc_email: 'razi.ansari@diligencevault.com',
      updated_by: 320,
      updated_at: '2024-09-12T11:48:12.187',
      regulatory_alert_frequency: 432,
      password_expiration_frequency: 365,
      password_reuse_limit: 1,
      logo_link:
        'https://dvfeatureenvstorage.blob.core.windows.net/images/firm2/Img-1714646570878_1714646571.png',
      disable_all_outbound_emails: false,
      disable_accept_decline_outbound_emails: false,
      set_materialADV_default: true,
      set_firm_entity_default: 'Firm',
      ui_version: 'Angular',
      module_ui_version:
        '{"questionnaire_ui_version":2,"template_ui_version":2,"parser_ui_version":2,"entity_modals_ui_version":2}',
      enable_questionnaire_numbering: true,
      enable_yaxis_entity: false,
      invert_color: false,
      set_preapproved_default: false,
      font_size: 13,
      font_color: '#191B1C',
      font_type: 6,
      exclude_empty_response: true,
      exclude_comments: true,
      split_comments: true,
      include_internal_key: false,
      enable_grid_numbering: true,
      transpose_excel_columns: false,
      default_daterange_months: 1,
      default_document_export_template_id: null,
      default_email_template_message_id: 181,
      disallow_custom_email_template_edit: false,
      color_codes: [
        '#264E86',
        '#20BF55',
        '#D14549',
        '#01BAEF',
        '#BAD75E',
        '#B576AD',
        '#757575',
        '#E6A71E',
      ],
      enable_category_instructions_export: true,
      enable_question_instructions_export: true,
      disable_response_followups: false,
      enable_system_document_tags: true,
      enable_system_strategies: true,
      enable_internal_notes_export: true,
      enable_followups_export: true,
      include_question_only_export: false,
      enable_notes_audit_export: true,
      enable_ratings_export: true,
      enableQASearch: true,
      enable_Review_Workflow: false,
      enable_track_changes: true,
      include_project_documents: true,
      review_workflow_mandatory_for_internal_diligence: false,
      review_workflow_mandatory_for_external_diligence: false,
      enable_internal_project_to_external_option: true,
      allow_review_template_in_standard_diligence: true,
      enable_rating_custom_fields_review: true,
      include_responses_excel_export: true,
      include_comments_excel_export: true,
      include_ratings_excel_export: true,
      enable_approval_flow_information_request: true,
      include_flags_excel_export: false,
      include_ratings_word_export: true,
      include_flags_word_export: true,
      enable_heatmap_dates: true,
      apply_ScoreRules_PreviousVersions: true,
      threshold_for_approval_flow: 5,
      approver_list_for_information_request: [320],
      excel_bulk_import: true,
      default_response_word_limit: null,
      enable_inbound_module: true,
      enable_new_qa_look: true,
      copy_manager_tags: true,
      show_presentation_module: true,
      enable_auto_entity_permissions: false,
      auto_entity_permission_default_role: 6,
      export_custom_report_draft_responses: false,
      enable_powerbi_reports: true,
      export_custom_report_all_checkboxes: false,
      default_user_access_role: null,
      grouped_by_attachment_columns_sharepoint:
        'owner_firm_id,associated_funds',
      folder_preferences_sharepoint: 'firm,type,as_of_date',
      issue_tracker_default_name: 'Open Diligence Items123',
      allow_external_issues: true,
      autofill_include_pre_approved: true,
      autofill_include_pre_approved_expired: true,
      autofill_include_standard: true,
      autofill_prioritize_most_recent: true,
      autofill_restrict_same_entity: false,
      autofill_restrict_same_requestor: false,
      autofill_restrict_modifications: false,
      autofill_enable_match_settings: true,
      autofill_match_settings_percentage: null,
      default_api_user: null,
      allow_restart_review_process: true,
      allow_only_authors_to_change_response: true,
      doc_access_preference: 'both',
      enable_custom_access_level: true,
      enable_es_autofill: true,
      default_permission_type: 1,
      default_permission_role: 8,
      enable_mandatory_permission_assignment: false,
      disable_project_info_popup: false,
      enable_gen_ai: true,
      enable_system_gen_ai: true,
      default_document_tab: 'Received',
      default_document_view: 'File',
      editor_version: 2,
      enable_auto_review_again: true,
    },
    allowRichTextarea: true,
    display_name: 'World Pensions test',
    is_owner: false,
    last_updated_at: null,
    tag_ids: null,
    permission_model:
      '[request_definition]\r\n\t\tr = role, resource, action\r\n\t\t[policy_definition]\r\n\t\tp = role, resource, action, eft\r\n\t\t[policy_effect]\r\n\t\t# There must be atleast one rule to allow and no rule to deny\r\n\t\te = some(where (p.eft == allow)) && !some(where (p.eft == deny))\r\n\t\t[matchers]\r\n\t\tm = keyMatch(r.role, p.role) && (keyMatch(r.resource, p.resource) || keyMatch2(r.resource, p.resource)) && regexMatch(r.action, p.action)',
    permission_policies:
      'p, Newly Added Role, /api/document_folders/delete_multiple, POST, allow\rp, Newly Added Role, /api/document_folders/paste, POST, allow\rp, Newly Added Role, /api/document_folders/:id, PUT, allow\rp, Newly Added Role, /api/v2/attachments/update_multiple, POST, allow\rp, Newly Added Role, /api/attachments/:id, PUT, allow\rp, Newly Added Role, /api/service/dv_scheduler_service/download_dir_blob, POST, allow\rp, Newly Added Role, /api/attachments/bulk_download, POST, allow\rp, Newly Added Role, /api/attachments/:id/signed_url, GET, allow\rp, Access level 3, /api/service/excel_services/presentation_report_upload/upload, POST, allow\rp, Access level 3, /api/reports/new/report_template_mapping, POST, allow\rp, Access level 3, /api/reports/new/generate, POST, allow\rp, Access level 3, /api/service/es_service/question_suggestions_new, POST, allow\rp, Access level 3, /api/templates/:id/bulk_sections, POST, allow\rp, Access level 3, /api/excel_parser/upload, POST, allow\rp, Access level 3, /api/grids, POST, allow\rp, Access level 3, /api/question_dropdowns, POST, allow\rp, Access level 3, /api/templates, POST, allow\rp, Access level 3, /api/sections/*, POST, allow\rp, Access level 3, /api/questions/*, POST, allow\rp, Access level 3, /api/excel_parser/create_template, POST, allow\rp, Access level 3, /api/sections/:id/nestedquestions, POST, allow\rp, Access level 3, /api/service/dvapi_service/post_custom_fields_data, POST, allow\rp, Access level 3, /api/contacts, POST, allow\rp, Access level 3, /api/firms/:id/funds/:id/vehicles, POST, allow\rp, Access level 3, /api/funds, POST, allow\rp, Access level 3, /api/firms, POST, allow\rp, Access level 3, /api/document_folders, POST, allow\rp, Access level 3, /api/v2/attachments/update_multiple, POST, allow\rp, Access level 3, /api/v2/attachments, POST, allow\rp, Access level 3, /api/attachmentassignments/bulk_assignment_v2, POST, allow\rp, Access level 3, /api/attachmentassignments/bulk_assignment, POST, allow\rp, Access level 3, /api/attachments, POST, allow\rp, Access level 3, /api/document_folders/delete_multiple, POST, allow\rp, Access level 3, /api/document_folders/paste, POST, allow\rp, Access level 3, /api/document_folders/:id, PUT, allow\rp, Access level 3, /api/v2/attachments/update_multiple, POST, allow\rp, Access level 3, /api/attachments/:id, PUT, allow\rp, Access level 3, /api/service/dv_scheduler_service/download_dir_blob, POST, allow\rp, Access level 3, /api/attachments/bulk_download, POST, allow\rp, Access level 3, /api/attachments/:id/signed_url, GET, allow\rp, Restricted, *, GET, allow\rp, Restricted, /app/firm/settings/*, GET, deny\rp, Restricted, /app/firm/settings/*, DELETE, deny\rp, Restricted, /app/firm/settings/*, POST, deny\rp, Restricted, /app/firm/settings/*, PUT, deny\rp, Restricted, /api/service/*, POST, allow\rp, SuperViewer, /api/service/*, POST, allow\rp, SuperViewer, /api/service/es_service/autofill_es, POST, deny\rp, SuperViewer, /api/service/dvapi_service/get_issues, POST, allow\rp, SuperViewer, /api/service/dvapi_service/issues, POST, allow\rp, SuperViewer, /api/service/dvapi_service/issue_comment, DELETE, deny\rp, SuperViewer, /api/service/dvapi_service/issue_comment, PUT, deny\rp, SuperViewer, /api/service/dvapi_service/issue_comment, POST, deny\rp, SuperViewer, /api/service/dvapi_service/issue, DELETE, deny\rp, SuperViewer, /api/service/dvapi_service/issue, PUT, deny\rp, SuperViewer, /api/service/dvapi_service/issue, POST, deny\rp, SuperViewer, /app/firm/settings/*, DELETE, deny\rp, SuperViewer, /app/firm/settings/*, POST, deny\rp, SuperViewer, /app/firm/settings/*, PUT, deny\rp, SuperViewer, /app/firm/settings/*, GET, deny\rp, SuperViewer, /api/service/dvapi_service/post_custom_fields_data, POST, deny\rp, SuperViewer, *, GET, allow\rp, SuperContributor, /api/service/es_service/autofill_es, POST, allow\rp, SuperContributor, /api/v2/diligences/bulk_actions/evaluation, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/inreview, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/extensiondeclined, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/extensionapproved, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/extensionrequested, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/restartapproved, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/restarted, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/pendingrestart, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/deleted, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/notapproved, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/approved, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/completed, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/started, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/withdrawn, PUT, deny\rp, SuperContributor, /api/v2/diligences/bulk_actions/reminded, PUT, deny\rp, SuperContributor, /api/service/es_service/autofill_es, POST, allow\rp, SuperContributor, /api/diligences/:id/evaluation, PUT, deny\rp, SuperContributor, /api/diligences/:id/inreview, PUT, deny\rp, SuperContributor, /api/diligences/:id/extensiondeclined, PUT, deny\rp, SuperContributor, /api/diligences/:id/extensionapproved, PUT, deny\rp, SuperContributor, /api/diligences/:id/extensionrequested, PUT, deny\rp, SuperContributor, /api/diligences/:id/restartapproved, PUT, deny\rp, SuperContributor, /api/diligences/:id/restarted, PUT, deny\rp, SuperContributor, /api/diligences/:id/pendingrestart, PUT, deny\rp, SuperContributor, /api/diligences/:id/deleted, PUT, deny\rp, SuperContributor, /api/diligences/:id/notapproved, PUT, deny\rp, SuperContributor, /api/diligences/:id/approved, PUT, deny\rp, SuperContributor, /api/diligences/:id/completed, PUT, deny\rp, SuperContributor, /api/diligences/:id/started, PUT, allow\rp, SuperContributor, /api/diligences/:id/withdrawn, PUT, deny\rp, SuperContributor, /api/diligences/:id/reminded, PUT, deny\rp, SuperContributor, /api/diligences/:id/autofill_ratings, POST, allow\rp, SuperContributor, *, PATCH, allow\rp, SuperContributor, /api/responses/:id/status, PATCH, allow\rp, SuperContributor, /api/response_comments, POST, allow\rp, SuperContributor, /api/diligences/:id/update_data, PUT, deny\rp, SuperContributor, /api/diligences/:id, PUT, deny\rp, SuperContributor, /app/firm/settings/*, DELETE, deny\rp, SuperContributor, /app/firm/settings/*, POST, deny\rp, SuperContributor, /app/firm/settings/*, PUT, deny\rp, SuperContributor, /app/firm/settings/*, GET, deny\rp, SuperContributor, /api/templates/*, DELETE, deny\rp, SuperContributor, /api/templates/*, POST, deny\rp, SuperContributor, /api/service/excel_services/aum_tr_upload/upload, POST, deny\rp, SuperContributor, /api/service/excel_services/aum_tr_download, POST, deny\rp, SuperContributor, /api/attachments/update_metadata, POST, allow\rp, SuperContributor, /api/entity_approvals, POST, allow\rp, SuperContributor, /api/diligences/:id/mark_as_external, PUT, deny\rp, SuperContributor, /api/workflow_audits/:id, DELETE, deny\rp, SuperContributor, /api/diligences/:id/assign_reviewer, POST, allow\rp, SuperContributor, /api/service/*, POST, allow\rp, SuperContributor, /api/diligences/:id/responses/:id/reset_review, POST, allow\rp, SuperContributor, /api/v2/attachments/update_multiple, POST, allow\rp, SuperContributor, /api/v2/attachments, POST, allow\rp, SuperContributor, /api/document_folders, POST, allow\rp, SuperContributor, /api/attachmentassignments/bulk_assignment_v2, POST, allow\rp, SuperContributor, /api/followups/bulk_add, POST, allow\rp, SuperContributor, /api/entity_reviews, POST, allow\rp, SuperContributor, /api/v2/attachments/update_multiple, POST, allow\rp, SuperContributor, /api/document_folders/paste, POST, allow\rp, SuperContributor, /api/document_folders/delete_multiple, POST, allow\rp, SuperContributor, /api/document_folders/:id, PUT, allow\rp, SuperContributor, /api/v2/attachments/update_multiple, POST, allow\rp, SuperContributor, /api/document_folders/paste, POST, allow\rp, SuperContributor, /api/document_folders/delete_multiple, POST, allow\rp, SuperContributor, /api/document_folders/:id, PUT, allow\rp, SuperContributor, /api/v2/attachments/update_multiple, POST, allow\rp, SuperContributor, /api/v2/attachments, POST, allow\rp, SuperContributor, /api/document_folders, POST, allow\rp, SuperContributor, /api/attachmentassignments/bulk_assignment_v2, POST, allow\rp, SuperContributor, /api/notes, POST, allow\rp, SuperContributor, /api/sequences, POST, allow\rp, SuperContributor, /api/dd_duedate_extensions, POST, deny\rp, SuperContributor, /api/aumtrackrecorddefinitions/:id/aumtrackrecordvalues, POST, allow\rp, SuperContributor, /api/attachmentassignments/bulk_assignment, POST, allow\rp, SuperContributor, /api/attachmentassignments, POST, allow\rp, SuperContributor, /api/attachments, POST, allow\rp, SuperContributor, /api/v2/diligences/autofill, POST, allow\rp, SuperContributor, /api/notes, POST, allow\rp, SuperContributor, /api/entity_events, POST, allow\rp, SuperContributor, /api/todos, POST, allow\rp, SuperContributor, /api/followups, POST, allow\rp, SuperContributor, /api/entitysubscribers, POST, allow\rp, SuperContributor, /api/templates/:id/clone, POST, deny\rp, SuperContributor, /api/entitysubscribers, DELETE, deny\rp, SuperContributor, /api/templates/:id/activate, PATCH, deny\rp, SuperContributor, /api/responses/:id/track_status, PATCH, allow\rp, SuperContributor, /api/diligences/:id/responses/:id/bulk_resolve_comments, PUT, allow\rp, SuperContributor, /api/templates/*, PUT, deny\rp, SuperContributor, /api/sections/*, DELETE, deny\rp, SuperContributor, /api/sections/*, POST, deny\rp, SuperContributor, /api/sections/*, PUT, deny\rp, SuperContributor, /api/questions/*, DELETE, deny\rp, SuperContributor, /api/questions/*, POST, deny\rp, SuperContributor, /api/questions/*, PUT, deny\rp, SuperContributor, *, DELETE, allow\rp, SuperContributor, *, PUT, allow\rp, SuperContributor, *, GET, allow\rp, SuperOwner, /app/firm/settings/*, GET, deny\rp, SuperOwner, /app/firm/settings/*, DELETE, deny\rp, SuperOwner, /app/firm/settings/*, POST, deny\rp, SuperOwner, /app/firm/settings/*, PUT, deny\rp, SuperOwner, *, GET, allow\rp, SuperOwner, *, PATCH, allow\rp, SuperOwner, *, DELETE, allow\rp, SuperOwner, /api/service/dv_scheduler_service/download_dir_blob, POST, allow\rp, SuperOwner, /api/v2/attachments/update_multiple, POST, allow\rp, SuperOwner, /api/document_folders/paste, POST, allow\rp, SuperOwner, /api/document_folders/delete_multiple, POST, allow\rp, SuperOwner, /api/document_folders/:id, PUT, allow\rp, SuperOwner, /api/v2/attachments/update_multiple, POST, allow\rp, SuperOwner, /api/v2/attachments, POST, allow\rp, SuperOwner, /api/document_folders, POST, allow\rp, SuperOwner, /api/attachmentassignments/bulk_assignment_v2, POST, allow\rp, SuperOwner, /api/v2/attachments/update_multiple, POST, allow\rp, SuperOwner, /api/document_folders/paste, POST, allow\rp, SuperOwner, *, POST, allow\rp, SuperOwner, *, PUT, allow\rp, SuperOwner, /api/diligences/:id/responses/:id/reset_review, POST, allow\rp, SuperOwner, /api/document_folders/delete_multiple, POST, allow\rp, SuperOwner, /api/document_folders/:id, PUT, allow\rp, SuperOwner, /api/v2/attachments/update_multiple, POST, allow\rp, SuperOwner, /api/v2/attachments, POST, allow\rp, SuperOwner, /api/service/*, POST, allow\rp, SuperOwner, /api/document_folders, POST, allow\rp, SuperOwner, /api/attachmentassignments/bulk_assignment_v2, POST, allow\rp, SecurityAdmin, /api/service/*, POST, allow\rp, SecurityAdmin, /app/firm/settings/access_levels, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/access_levels, PATCH, allow\rp, SecurityAdmin, /app/firm/settings/access_levels, PUT, allow\rp, SecurityAdmin, /app/firm/settings/access_levels, POST, allow\rp, SecurityAdmin, /app/firm/settings/access_levels, GET, allow\rp, SecurityAdmin, /api/users, POST, allow\rp, SecurityAdmin, /api/rating_scheme_defaults/system, PUT, deny\rp, SecurityAdmin, /api/rating_schemes/:id/rating_scores_analysis, POST, deny\rp, SecurityAdmin, /api/attachments/bulk_download, POST, deny\rp, SecurityAdmin, *, GET, allow\rp, SecurityAdmin, /app/firm/settings/teams, GET, allow\rp, SecurityAdmin, /app/firm/settings/teams, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/teams, POST, allow\rp, SecurityAdmin, /app/firm/settings/teams, PUT, allow\rp, SecurityAdmin, /app/firm/settings/sso-profile, GET, allow\rp, SecurityAdmin, /app/firm/settings/sso-profile, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/sso-profile, POST, allow\rp, SecurityAdmin, /app/firm/settings/sso-profile, PUT, allow\rp, SecurityAdmin, /app/firm/settings/permissions, GET, allow\rp, SecurityAdmin, /app/firm/settings/permissions, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/permissions, POST, allow\rp, SecurityAdmin, /app/firm/settings/permissions, PUT, allow\rp, SecurityAdmin, /app/firm/settings/permission/detail, GET, allow\rp, SecurityAdmin, /app/firm/settings/permission/detail, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/permission/detail, POST, allow\rp, SecurityAdmin, /app/firm/settings/permission/detail, PUT, allow\rp, SecurityAdmin, /app/firm/settings/password, GET, allow\rp, SecurityAdmin, /app/firm/settings/password, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/password, POST, allow\rp, SecurityAdmin, /app/firm/settings/password, PUT, allow\rp, SecurityAdmin, /app/firm/settings/ip_configurations, GET, allow\rp, SecurityAdmin, /app/firm/settings/ip_configurations, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/ip_configurations, POST, allow\rp, SecurityAdmin, /app/firm/settings/ip_configurations, PUT, allow\rp, SecurityAdmin, /app/firm/settings/functions, GET, allow\rp, SecurityAdmin, /app/firm/settings/functions, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/functions, POST, allow\rp, SecurityAdmin, /app/firm/settings/functions, PUT, allow\rp, SecurityAdmin, /app/firm/settings/employees, GET, allow\rp, SecurityAdmin, /app/firm/settings/employees, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/employees, POST, allow\rp, SecurityAdmin, /app/firm/settings/employees, PUT, allow\rp, SecurityAdmin, /app/firm/settings/domains, GET, allow\rp, SecurityAdmin, /app/firm/settings/domains, DELETE, allow\rp, SecurityAdmin, /app/firm/settings/domains, POST, allow\rp, SecurityAdmin, /app/firm/settings/domains, PUT, allow\rp, SecurityAdmin, /api/attachments, GET, deny\rp, SecurityAdmin, /api/service/es_service/qa_search_v1, POST, deny\rp, SecurityAdmin, /api/service/es_service/qa_search, POST, deny\rp, SecurityAdmin, /api/subscriptions, GET, deny\rp, SecurityAdmin, /api/attachments/search, GET, deny\rp, SecurityAdmin, /api/calendar_sync, GET, deny\rp, SecurityAdmin, /api/outlook_preferences, GET, deny\rp, BusinessAdmin, /app/firm/settings/sso-profile, GET, deny\rp, BusinessAdmin, /app/firm/settings/sso-profile, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/sso-profile, POST, deny\rp, BusinessAdmin, /app/firm/settings/sso-profile, PUT, deny\rp, BusinessAdmin, /app/firm/settings/password, GET, deny\rp, BusinessAdmin, /app/firm/settings/password, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/password, POST, deny\rp, BusinessAdmin, /app/firm/settings/password, PUT, deny\rp, BusinessAdmin, /app/firm/settings/ip_configurations, GET, deny\rp, BusinessAdmin, /app/firm/settings/ip_configurations, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/ip_configurations, POST, deny\rp, BusinessAdmin, /app/firm/settings/ip_configurations, PUT, deny\rp, BusinessAdmin, /app/firm/settings/functions, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/functions, POST, deny\rp, BusinessAdmin, /app/firm/settings/functions, PUT, deny\rp, BusinessAdmin, /app/firm/settings/employees, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/employees, POST, deny\rp, BusinessAdmin, /app/firm/settings/domains, GET, deny\rp, BusinessAdmin, /app/firm/settings/domains, PATCH, deny\rp, BusinessAdmin, /app/firm/settings/domains, DELETE, deny\rp, BusinessAdmin, /app/firm/settings/domains, POST, deny\rp, BusinessAdmin, /app/firm/settings/domains, PUT, deny\rp, BusinessAdmin, *, GET, allow\rp, BusinessAdmin, *, PATCH, allow\rp, BusinessAdmin, *, DELETE, allow\rp, BusinessAdmin, *, POST, allow\rp, BusinessAdmin, *, PUT, allow\rp, BusinessAdmin, /app/firm/settings/permission/detail, DELETE, allow\rp, BusinessAdmin, /app/firm/settings/permission/detail, POST, allow\rp, BusinessAdmin, /app/firm/settings/permission/detail, PUT, allow\rp, BusinessAdmin, /app/firm/settings/permissions, DELETE, allow\rp, BusinessAdmin, /app/firm/settings/permissions, POST, allow\rp, BusinessAdmin, /app/firm/settings/permissions, PUT, allow\rp, BusinessAdmin, /app/firm/settings/teams, DELETE, allow\rp, BusinessAdmin, /app/firm/settings/teams, POST, allow\rp, BusinessAdmin, /app/firm/settings/teams, PUT, allow\rp, BusinessAdmin, /app/firm/settings/employees, PATCH, allow\rp, BusinessAdmin, /app/firm/settings/employees, PUT, allow\rp, BusinessAdmin, /api/service/*, POST, allow\rp, SuperAdmin, /api/service/*, POST, allow\rp, SuperAdmin, *, PATCH, allow\rp, SuperAdmin, *, DELETE, allow\rp, SuperAdmin, *, POST, allow\rp, SuperAdmin, *, PUT, allow\rp, SuperAdmin, *, GET, allow\rp, *, /api/service/dvapi_service/download_audit, POST, allow\rp, *, /api/gridviews, DELETE, allow\rp, *, /api/gridviews, POST, allow\rp, *, /api/gridviews/:id, PATCH, allow\rp, *, /api/gridviews/:id, PUT, allow\rp, *, /api/service/excel_services/bulk_word_export, POST, allow\rp, *, /api/document_statistics, POST, allow\rp, *, /api/document_statistics, POST, allow\rp, *, /api/reusable_predefined_documents_tags, POST, allow\rp, *, /api/service/dvapi_service/download_task_file, POST, allow\rp, *, /api/service/excel_services/word_export, POST, allow\rp, *, /api/service/excel_services/diligence_report, POST, allow\rp, *, /api/service/excel_services/diligence_questions, POST, allow\rp, *, /api/service/es_service/search, POST, allow\rp, *, /api/service/es_service/filters, POST, allow\rp, *, /api/service/dvapi_service/get_issue_comments, POST, allow\rp, *, /api/service/es_service/qa_recommendation, POST, allow\rp, *, /api/service/es_service/firm_last_updation, POST, allow\rp, *, /api/service/es_service/qa_search_v1, POST, allow\rp, *, /api/service/es_service/qa_filters_v1, POST, allow\rp, *, /api/service/excel_services/aum_tr_download, POST, allow\rp, *, /api/service/es_service/question_suggestions, POST, allow\rp, *, /api/service/es_service/question_filters, POST, allow\rp, *, /api/diligences/:id/followups/getfollowupsbyresponseids, POST, allow\rp, *, /api/service/dvapi_service/get_issues, POST, allow\rp, *, /api/service/dvapi_service/get_issue_count, POST, allow\rp, *, /api/service/dvapi_service/get_custom_fields_data, POST, allow\rp, *, /api/service/dvapi_service/diligence_search, POST, allow\rp, *, /api/service/dvapi_service/firm_search, POST, allow\rp, *, /api/service/dvapi_service/vehicle_search, POST, allow\rp, *, /api/service/dvapi_service/product_search, POST, allow\rp, *, /api/service/dvapi_service/contact_search, POST, allow\rp, *, /api/service/dvapi_service/fund_search, POST, allow\rp, *, /api/service/dvapi_service/search_filters, POST, allow\rp, *, /api/service/dvapi_service/get_custom_fields, POST, allow\rp, *, *, GET, allow\rp, *, /api/diligences/counts, GET, allow\rp, *, /api/notifications, GET, allow\rp, *, /api/nudges, GET, allow\rp, *, /api/firm_preferences, GET, allow\rp, *, /api/feedback_types, GET, allow\rp, *, /api/users/:id/associated_firms, GET, allow\rp, *, /api/function_assignments, GET, allow\rp, *, /api/functions, GET, allow\rp, *, /api/users/me, GET, allow\rp, *, /api/V2/GridStates, GET, allow\rp, *, /api/notifications/*, GET, allow\rp, *, /api/user_notification_settings, GET, allow\rp, *, /api/subscription_limits, GET, allow\rp, *, /api/team_members, GET, allow\rp, *, /api/account, GET, allow\rp, *, /api/GridStates, GET, allow\rp, *, /api/operators, GET, allow\rp, *, /api/saml/login, GET, allow\rp, *, /api/nestingrules/get_rules, POST, allow\rp, *, /api/users/review_intro, PATCH, allow\rp, *, /api/intro_modals, PUT, allow\rp, *, /api/review_projects/responses, POST, allow\rp, *, /api/notifications/*, HEAD, allow\rp, *, /api/outlook_preferences, PUT, allow\rp, *, /api/rating_scheme_defaults/system, PUT, allow\rp, *, /api/rating_schemes/:id/rating_scores_analysis, POST, allow\rp, *, /api/attachments/bulk_download, POST, allow\rp, *, /api/nudges/log, POST, allow\rp, *, /api/permissionurls, GET, allow\rp, *, /api/workflow_actions, GET, allow\rp, *, /api/feedback, POST, allow\rp, *, /api/notifications/*, PUT, allow\rp, *, /api/notifications/*, POST, allow\rp, *, /api/notifications/*, GET, allow\rp, *, /api/refreshtokens, DELETE, allow\rp, *, /api/users/certify, POST, allow\rp, *, /api/two_factor_authentication/configure, POST, allow\rp, *, /api/user_notification_settings, PUT, allow\rp, *, /api/account/changepassword, PUT, allow\rp, *, /api/users/:id, PUT, allow\r',
    modules_json: null,
    hasPermissionEnabled: true,
    permissions: null,
    allowed_teams: 2,
    ui_version: 0,
    functions: [],
    display_duplicate_warning: false,
    new_firm_created: false,
    sso_entity_id_version: 0,
    domain_name: null,
  },
  accessLevel: 'Admin',
  accessLevelID: 0,
  isAdmin: true,
  isReadOnly: false,
  is_approver: false,
  active: true,
  country: null,
  avatarURL: null,
  title: null,
  psk: 'BBCFPEDPXGCB7JXV',
  twoFactorEnabled: false,
  anonymous: false,
  bounced_at: null,
  phone: null,
  eucAccepted: true,
  group_by_intro: true,
  review_functionality_intro: true,
  discussEUCAccepted: true,
  isFirstLogin: false,
  firmAccessCount: 3,
  conversionDateTime: '2018-01-02T00:25:48',
  isFirstDD: false,
  isFirstTemplate: false,
  statusCode: 0,
  fundId: 0,
  lastTouchPoint: null,
  owner_user_id: null,
  owner_name: null,
  contact_type_ids: null,
  contact_types: null,
  type_ids: null,
  street_address_1: null,
  street_address_2: null,
  city: null,
  state: null,
  zipcode: null,
  country_id: 0,
  phone_1: null,
  phone_2: null,
  fax: null,
  relationship_status_id: 0,
  relationship_status: null,
  associated_funds: [],
  associated_programs: [],
  associated_strategies: [],
  lockoutEndDateUtc: null,
  key: null,
  firm_name: 'World Pensions test',
  is_tracking: false,
  is_verified: false,
  is_owner: false,
  is_new_user: false,
  skip_tour: true,
  approved_by: 2,
  approved_at: '2020-03-13T07:21:25',
  send_invitation: false,
  can_change_firm: false,
  last_updated_at: null,
  api_key: null,
  firmwide_role: 'SuperAdmin',
  firmwide_role_alias: 'Super Admin',
  firmwide_role_id: 0,
  is_saml_enabled: false,
  platform_active: false,
  relationship_active: false,
};
export const me = {
  associated_firms_count: 0,
  recaptchaToken: null,
  signupVerificationCode: null,
  referral_data: null,
  is_default: false,
  userName: 'investors@diligencevault.com',
  password: null,
  confirmPassword: null,
  newPassword: null,
  id: 0,
  type: 0,
  firstName: 'investor',
  lastName: 'account',
  fullName: 'investor account',
  firmInfo: {
    notification_contacts: [],
    id: 0,
    name: 'World Pensions test',
    firm_type_id: 0,
    firm_type: null,
    subscription: 'Free',
    accessProfile: 0,
    website: null,
    inceptionDate: null,
    expiryDate: '0001-01-01T00:00:00',
    aum: 0.0,
    currency: null,
    currencyID: 0,
    contactPerson: null,
    contacts: null,
    firmDescription: null,
    isInvestor: false,
    isDocToHtmlEnabled: false,
    api_key: null,
    lastTouchPoint: null,
    owner_user_id: null,
    owner_name: null,
    relationship_status_id: null,
    relationship_status_name: null,
    active: false,
    admin_user_email: null,
    key: null,
    alternate_name: null,
    email_domain: null,
    is_tracking: false,
    preferences: null,
    allowRichTextarea: true,
    display_name: 'World Pensions test',
    is_owner: false,
    last_updated_at: null,
    tag_ids: null,
    permission_model: null,
    permission_policies: null,
    modules_json: null,
    hasPermissionEnabled: false,
    permissions: null,
    allowed_teams: 0,
    ui_version: 0,
    functions: [],
    display_duplicate_warning: false,
    new_firm_created: false,
    sso_entity_id_version: 0,
    domain_name: null,
  },
  accessLevel: 'Admin',
  accessLevelID: 0,
  isAdmin: false,
  isReadOnly: false,
  is_approver: false,
  active: false,
  country: 'St Helena',
  avatarURL: null,
  title: 'title',
  psk: null,
  twoFactorEnabled: false,
  anonymous: false,
  bounced_at: null,
  phone: null,
  eucAccepted: false,
  group_by_intro: false,
  review_functionality_intro: false,
  discussEUCAccepted: false,
  isFirstLogin: true,
  firmAccessCount: 0,
  conversionDateTime: null,
  isFirstDD: true,
  isFirstTemplate: true,
  statusCode: 0,
  fundId: 0,
  lastTouchPoint: null,
  owner_user_id: null,
  owner_name: null,
  contact_type_ids: null,
  contact_types: null,
  type_ids: null,
  street_address_1: '1',
  street_address_2: null,
  city: 'a',
  state: 'gujarat',
  zipcode: '3880059',
  country_id: 677,
  phone_1: '99048445178',
  phone_2: null,
  fax: null,
  relationship_status_id: 0,
  relationship_status: null,
  associated_funds: [],
  associated_programs: [],
  associated_strategies: [],
  lockoutEndDateUtc: null,
  key: null,
  firm_name: 'World Pensions test',
  is_tracking: false,
  is_verified: false,
  is_owner: false,
  is_new_user: false,
  skip_tour: false,
  approved_by: null,
  approved_at: null,
  send_invitation: false,
  can_change_firm: false,
  last_updated_at: null,
  api_key: null,
  firmwide_role: null,
  firmwide_role_alias: null,
  firmwide_role_id: 0,
  is_saml_enabled: false,
  platform_active: false,
  relationship_active: false,
};

export const mockAdminFeatureData = {
  me :null,
  account:null,
};
export const mockSecurityAdminFeatureData = {
  me :null ,
  account:null,
};

export const allFeatureData = {
  [ALL_USER_ROLE.ADMIN]: { ...commonData, ...mockAdminFeatureData },
  [ALL_USER_ROLE.SECURITY_ADMIN]: { ...commonData, ...mockSecurityAdminFeatureData },
};
