import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { SharedModule } from 'src/app2/shared/shared.module';
import {
  CategoryListComponent,
  DvDraftComponent,
  QuestionnaireHeaderComponent,
  QuestionnaireStartedComponent,
  QuestionnaireSubmitButtonComponent,
  QuestionsContainerComponent,
  QuickViewHeaderComponent,
  QaBankComponent,
  QaButtonTabsComponent,
  QaPreviewComponent,
  QuestionnaireReadonlyComponent,
  QuestionnaireInReviewComponent,
  QuestionnairePreApprovedComponent,
  QuestionnaireEvaluationComponent,
  RelatedProjectStatusComponent,
  AutofillEntitySettingsComponent,
  AutofillPreviewComponent,
  AutofillProjectSelectionComponent,
  AutofillContentSettingsComponent,
  AutofillHelpTextComponent,
  GeneratePresentationReportComponent,
} from './components';
import {
  FullResponseModal,
  EncryptModal,
  ExportModal,
  GeneratePresentationReportModal,
  TemplateInfoComponent,
  AutofillComponent,
  AssignReviwerComponent,
  AddDisclaimerComponent,
  ReviewCommentsComponent,
  ImportGridModal,
  ViewRelatedDiligencesComponent,
  EsAutofillComponent,
  AutofillHistoryComponent,
  AutofillHistoryDetailComponent,
} from './modals';
import { QuestionSearchComponent } from './components/question-search/question-search.component';
import {
  QuestionnaireComponent,
  DvTabComponent,
  PrintPreviewComponent,
} from './page';
import {
  QaRevisionComponent,
  NewWorkflowComponent,
  SuggestedResponsesComponent,
  TodosComponent,
  // FollowUpPanelComponent,
  MappedQuestionsComponent,
  ViewRulesComponent,
  ReviewStatusComponent,
  CkCommentsPanelComponent,
  CkOutsideCommentsPanelComponent,
  AiPanelComponent,
} from './side-panels';
import { QuestionnairePrintPreviewComponent } from './components/questionnaire-print-preview/questionnaire-print-preview.component';
import { QuestionSearchReviewComponent } from './components/question-search-review/question-search-review.component';
import { RecommendationModule } from '../recommendation/recommendation.module';
import { RouterModule } from '@angular/router';
import { QUESTIONNIARE_ROUTES } from './questionniare.routes';

@NgModule({
  declarations: [
    QuickViewHeaderComponent,
    QuestionnaireComponent,
    QuestionnaireHeaderComponent,
    QuestionSearchComponent,
    QuestionnaireSubmitButtonComponent,
    CategoryListComponent,
    QuestionsContainerComponent,
    DvDraftComponent,
    QaBankComponent,
    QaButtonTabsComponent,
    QaPreviewComponent,
    AutofillComponent,
    QuestionnaireStartedComponent,
    // FollowUpPanelComponent,
    SuggestedResponsesComponent,
    AssignReviwerComponent,
    QaRevisionComponent,
    NewWorkflowComponent,
    AssignReviwerComponent,
    FullResponseModal,
    AssignReviwerComponent,
    DvTabComponent,
    QuestionnaireReadonlyComponent,
    EncryptModal,
    ExportModal,
    GeneratePresentationReportModal,
    TodosComponent,
    QuestionnaireInReviewComponent,
    QuestionnairePreApprovedComponent,
    TemplateInfoComponent,
    AddDisclaimerComponent,
    ReviewCommentsComponent,
    MappedQuestionsComponent,
    ImportGridModal,
    QuestionnaireEvaluationComponent,
    PrintPreviewComponent,
    QuestionnairePrintPreviewComponent,
    RelatedProjectStatusComponent,
    ViewRelatedDiligencesComponent,
    ReviewStatusComponent,
    QuestionSearchReviewComponent,
    EsAutofillComponent,
    AutofillEntitySettingsComponent,
    AutofillPreviewComponent,
    AutofillHistoryComponent,
    AutofillProjectSelectionComponent,
    AutofillContentSettingsComponent,
    AutofillHelpTextComponent,
    ViewRulesComponent,
    GeneratePresentationReportComponent,
    AiPanelComponent,
    AutofillHistoryDetailComponent,
    CkCommentsPanelComponent,
    CkOutsideCommentsPanelComponent,
  ],
  imports: [
    CommonModule,
    SharedModule,
    RecommendationModule,
    RouterModule.forChild(QUESTIONNIARE_ROUTES),
  ],
  exports: [DvTabComponent, PrintPreviewComponent],
})
export class QuestionnaireModule {}
