import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { ColDef } from 'ag-grid-community';
import {
  defaultColumn,
  grid_widths_map,
} from 'src/app2/shared/constants/constant';
import { ReportsListType } from '../../type/report-list.type';

@Injectable({
  providedIn: 'root',
})
export class ReportListGridService {
  constructor(private readonly http: HttpClient) {}

  getMyReportListGridColDef(): ColDef[] {
    const colDef: ColDef[] = [];
    colDef.push({
      ...defaultColumn,
      colId: 'report_name',
      headerName: 'Report Name',
      field: 'report_name',
      filter: 'agTextColumnFilter',
      floatingFilter: true,
      floatingFilterComponent: 'textFloatingFilterComponent',
      floatingFilterComponentParams: {
        suppressFilterButton: true,
        placeHolder: 'Search by name',
      },
      flex: 1,
      minWidth: grid_widths_map.sm_column_sm,
      suppressColumnsToolPanel: true,
      cellStyle: {
        cursor: 'pointer',
      },
    });
    colDef.push({
      ...defaultColumn,
      colId: 'created_at',
      headerName: 'Generated On',
      menuTabs: ['generalMenuTab'],
      field: 'created_at',
      filter: 'agTextColumnFilter',
      flex: 1,
      minWidth: grid_widths_map.sm_column_xxm,
      cellStyle: {
        cursor: 'pointer',
      },
    });
    colDef.push({
      ...defaultColumn,
      colId: 'definition_name',
      headerName: 'Report Design Name',
      menuTabs: ['generalMenuTab'],
      field: 'definition_name',
      filter: 'agTextColumnFilter',
      floatingFilter: true,
      floatingFilterComponent: 'textFloatingFilterComponent',
      floatingFilterComponentParams: {
        suppressFilterButton: true,
        placeHolder: 'Search by definition',
      },
      flex: 1,
      minWidth: grid_widths_map.sm_column_xxm,
      cellStyle: {
        cursor: 'pointer',
      },
    });

    colDef.push({
      ...defaultColumn,
      colId: 'created_by',
      headerName: ' Generated By',
      menuTabs: ['generalMenuTab'],
      field: 'created_by',
      filter: 'agTextColumnFilter',
      floatingFilter: true,
      floatingFilterComponent: 'textFloatingFilterComponent',
      floatingFilterComponentParams: {
        suppressFilterButton: true,
        placeHolder: 'Search by created',
      },
      flex: 1,
      minWidth: grid_widths_map.sm_column_xxm,
      cellStyle: {
        cursor: 'pointer',
      },
    });
    colDef.push({
      ...defaultColumn,
      colId: 'as_of_date',
      headerName: 'As of Date',
      menuTabs: ['generalMenuTab'],
      field: 'as_of_date',
      filter: 'agTextColumnFilter',
      flex: 1,
      minWidth: grid_widths_map.sm_column_xxm,
      cellStyle: {
        cursor: 'pointer',
      },
    });

    return colDef;
  }

  getAllReports() {
    return this.http.get('reports');
  }
}
