import { CurrentUserModel } from 'src/app2/store/user/user.model';

export const allFiltersMap = {
  AssignedTotal: {
    name: 'Assignments - ME',
    icon: 'user',
    param: 'Assigned',
    countParam: 'AssignedTotal',
    count: undefined,
    color: 'default',
  },
  ToDoTotal: {
    name: 'To-Dos / Drafts',
    icon: 'tasks',
    param: 'Todo',
    countParam: 'ToDoTotal',
    count: undefined,
    color: 'default',
  },
  AnsweredTotal: {
    name: 'Answered',
    icon: 'check-circle',
    param: 'Answered',
    countParam: 'AnsweredTotal',
    count: undefined,
    color: 'default',
  },
  UnAnsweredTotal: {
    name: 'Unanswered',
    icon: 'radio-unchecked',
    param: 'Unanswered',
    countParam: 'UnAnsweredTotal',
    count: undefined,
    color: 'default',
  },
  MandatoryTotal: {
    name: 'Mandatory',
    icon: 'star-check-mark',
    param: 'MandatoryQuestions',
    countParam: 'MandatoryTotal',
    count: undefined,
    color: 'default',
  },
  MandatoryUnansweredTotal: {
    name: 'Mandatory Unanswered',
    icon: 'star-check-mark',
    param: 'MandatoryUnansweredTotal',
    countParam: 'MandatoryUnansweredTotal',
    count: undefined,
    color: 'default',
  },
  NATotal: {
    name: 'Not Applicable',
    icon: 'ban',
    param: 'NA',
    countParam: 'NATotal',
    count: undefined,
    color: 'default',
  },
  OpenFollowupTotal: {
    name: 'Open Follow-ups',
    icon: 'doubt',
    isDropdown: true,
    param: ['OpenFollowup', 'OpenSentFollowup', 'OpenReceivedFollowup'],
    countParam: 'OpenFollowupTotal',
    count: undefined,
    color: 'default',
    dropdownList: [
      {
        label: 'All',
        key: 'OpenFollowup',
        count: null,
        param: 'OpenFollowup',
        countParam: 'OpenFollowupTotal',
      },
      {
        label: 'Awaiting Follow-Up Responses',
        key: 'OpenSentFollowup',
        count: null,
        param: 'OpenSentFollowup',
        countParam: 'OpenSentFollowup',
      },
      {
        label: 'Received Follow-Ups',
        key: 'OpenReceivedFollowup',
        param: 'OpenReceivedFollowup',
        count: null,
        countParam: 'OpenReceivedFollowup',
      },
    ],
  },
  OpenFollowup: {
    name: 'All',
    icon: 'doubt',
    param: 'OpenFollowup',
    color: 'default',
  },
  OpenSentFollowup: {
    name: 'Awaiting Follow-Up Responses',
    icon: 'doubt',
    param: 'OpenSentFollowup',
    color: 'default',
  },
  OpenReceivedFollowup: {
    name: 'Received Follow-Ups',
    icon: 'doubt',
    param: 'OpenReceivedFollowup',
    color: 'default',
  },
  ResolvedFollowupTotal: {
    name: 'Resolved Follow-ups',
    icon: 'doubt',
    isDropdown: true,
    param: [
      'ResolvedFollowup',
      'ExternalResolvedFollowup',
      'InternalResolvedFollowup',
    ],
    countParam: 'ResolvedFollowupTotal',
    count: undefined,
    color: 'default',
    dropdownList: [
      {
        label: 'All',
        key: 'ResolvedFollowup',
        count: null,
        param: 'ResolvedFollowup',
        countParam: 'ResolvedFollowupTotal',
      },
      {
        label: 'Externally Resolved Follow-ups',
        key: 'ExternalResolvedFollowup',
        count: null,
        param: 'ExternalResolvedFollowup',
        countParam: 'ExternalResolvedFollowup',
      },
      {
        label: 'Internally Resolved Follow-ups',
        key: 'InternalResolvedFollowup',
        param: 'InternalResolvedFollowup',
        count: null,
        countParam: 'InternalResolvedFollowup',
      },
    ],
  },
  ResolvedFollowup: {
    name: 'All',
    icon: 'doubt',
    param: 'ResolvedFollowup',
    color: 'default',
  },
  ExternalResolvedFollowup: {
    name: 'Externally Resolved Follow-ups',
    icon: 'doubt',
    param: 'ExternalResolvedFollowup',
    color: 'default',
  },
  InternalResolvedFollowup: {
    name: 'Internally Resolved Follow-ups',
    icon: 'doubt',
    param: 'InternalResolvedFollowup',
    color: 'default',
  },
  SubmittedRevisionsCount: {
    name: 'Submitted Revisions to Requestor',
    icon: 'doubt',
    param: 'SubmittedRevisions',
    countParam: 'SubmittedRevisionsCount',
    count: undefined,
    color: 'default',
  },
  ResponsesWithRevisionsCount: {
    name: 'Responses with Revisions',
    icon: 'doubt',
    param: 'ResponsesWithRevisions',
    countParam: 'ResponsesWithRevisionsCount',
    count: undefined,
    color: 'default',
  },
  ScoredTotal: {
    name: 'Scored / Rated',
    icon: 'rating',
    param: 'Scored',
    countParam: 'ScoredTotal',
    count: undefined,
    hidden_from: ['manager'],
    color: 'default',
  },
  FlaggedTotal: {
    name: 'Flagged',
    icon: 'flag',
    param: 'Flagged',
    countParam: 'FlaggedTotal',
    count: undefined,
    hidden_from: ['manager'],
    color: 'default',
  },
  ExcludedFromRatingsCount: {
    name: 'Excluded From Ratings',
    icon: 'doubt',
    param: 'ExcludedRatings',
    countParam: 'ExcludedFromRatingsCount',
    count: undefined,
    hidden_from: ['manager'],
    color: 'default',
  },
  ExpiredTotal: {
    name: 'Expired',
    icon: 'times-up',
    param: 'Expired',
    countParam: 'ExpiredTotal',
    count: undefined,
    hidden_from: ['investor'],
    show_for_dd: ['dd_profile'],
    color: 'default',
  },
  VerificationMyAssignmentTotal: {
    name: 'Pending Verification - ME',
    icon: 'user-wait',
    param: 'VerificationMyAssignment',
    countParam: 'VerificationMyAssignmentTotal',
    count: undefined,
    hidden_from: ['investor'],
    show_for_dd: ['dd_profile'],
    color: 'default',
  },
  TotalReviewerAssignmentPending: {
    name: 'No Reviewers Assigned',
    icon: 'user-wait',
    param: 'TotalReviewerAssignmentPending',
    countParam: 'TotalReviewerAssignmentPending',
    count: undefined,
    color: 'default',
  },
  ReviewFailed: {
    name: 'Failed Reviews',
    icon: 'user-wait',
    param: 'ReviewFailed',
    countParam: 'ReviewFailed',
    count: undefined,
    color: 'default',
  },
  InReviewMyAssignments: {
    name: 'Reviews - ME',
    icon: 'user-wait',
    param: 'InReviewMyAssignments',
    countParam: 'InReviewMyAssignments',
    count: undefined,
    color: 'default',
  },
  WithTrackChangesCount: {
    name: 'Unresolved Track Changes',
    icon: 'compare',
    param: 'WithTrackChanges',
    countParam: 'WithTrackChangesCount',
    count: undefined,
    color: 'default',
  },
  RatingReviewpendingCount: {
    name: 'Rating Requiring Review',
    icon: 'rating',
    param: 'RatingReviewpendingCount',
    countParam: 'RatingReviewpendingCount',
    count: undefined,
    color: 'default',
    redirectionUrl: 'app.diligence.project.investment_ratings',
    redirectionParams: { diligenceId: null },
  },
  MyRatingReviewpendingCount: {
    name: 'Ratings Requring Review - ME',
    icon: 'rating',
    param: 'MyRatingReviewpendingCount',
    countParam: 'MyRatingReviewpendingCount',
    count: undefined,
    redirectionUrl: 'app.diligence.project.investment_ratings',
    redirectionParams: { diligenceId: null },
    color: 'default',
  },
  RatingAssignmentpendingCount: {
    name: 'No Rating Reviewer Assigned',
    icon: 'rating',
    param: 'RatingAssignmentpendingCount',
    countParam: 'RatingAssignmentpendingCount',
    count: undefined,
    redirectionUrl: 'app.diligence.project.investment_ratings',
    redirectionParams: { diligenceId: null },
    color: 'default',
  },
  RatingReviewFailed: {
    name: 'Failed Rating Review',
    icon: 'rating',
    param: 'RatingReviewFailed',
    countParam: 'RatingReviewFailed',
    count: undefined,
    redirectionUrl: 'app.diligence.project.investment_ratings',
    redirectionParams: { diligenceId: null },
    color: 'default',
  },
  TotalReviewPending: {
    name: 'All Pending Reviews',
    icon: 'user-wait',
    param: 'TotalReviewPending',
    countParam: 'TotalReviewPending',
    count: undefined,
    color: 'default',
  },
  TotalUnresolvedCommentsCount: {
    name: 'Unresolved Comments',
    icon: 'message-square',
    param: 'UnResolvedComments',
    countParam: 'TotalUnresolvedCommentsCount',
    count: undefined,
    color: 'default',
  },
  ValidationRequiredCount: {
    name: 'Responses With Validation Error',
    icon: 'table-with-check',
    param: 'ValidationRequired',
    countParam: 'ValidationRequiredCount',
    count: undefined,
    color: 'default',
  },
  AutoFilledResponses: {
    name: 'Auto-filled Responses',
    isDropdown: true,
    icon: 'auto-fill',
    param:
      ['AutoFilledResponses', 'ExactMatchAutofill', 'PartialMatchAutofill'] ||
      '',
    countParam: 'AutoFilledResponses',
    count: undefined,
    color: 'default',
    dropdownList: [
      {
        label: '100% Match',
        key: 'ExactMatchAutofillCount',
        count: null,
        param: 'ExactMatchAutofill',
        countParam: 'ExactMatchAutofillCount',
      },
      {
        label: 'Less than 100%',
        key: 'PartialMatchAutofillCount',
        countParam: 'PartialMatchAutofillCount',
        count: null,
        param: 'PartialMatchAutofill',
      },
    ],
  },
  ExactMatchAutofillCount: {
    name: '100% Match',
    icon: 'auto-fill',
    param: 'ExactMatchAutofill',
    color: 'default',
  },
  PartialMatchAutofillCount: {
    name: 'Less than 100%',
    icon: 'auto-fill',
    param: 'PartialMatchAutofill',
    color: 'default',
  },
};

export const filterForRole = (diligence) => {
  return {
    investor: {
      dd_new: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'AutoFilledResponses',

          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_profile: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'AutoFilledResponses',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'TotalUnresolvedCommentsCount',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
        ],
      },
      dd_ongoing: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'AutoFilledResponses',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_event_related: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'AutoFilledResponses',
          'UnAnsweredTotal',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_doc: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_internal: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'AutoFilledResponses',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
        ],
      },
      shared_profile: {
        main: [
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          diligence.is_internal &&
            !diligence.completed_at &&
            'ValidationRequiredCount',
        ],
      },
      review_project_pre: {
        main: [
          diligence.is_internal && 'TotalReviewPending',
          diligence.is_internal && 'TotalReviewerAssignmentPending',
          diligence.is_internal && 'ReviewFailed',
          'AutoFilledResponses',
          diligence.is_internal && 'InReviewMyAssignments',
          diligence.is_internal && 'WithTrackChangesCount',
        ],
        optional: [
          'TotalUnresolvedCommentsCount',
          diligence.is_internal && 'AssignedTotal',
          'ToDoTotal',
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          diligence.is_internal && 'ValidationRequiredCount',
          'NATotal',
        ],
      },
      review_project_post: {
        main: [
          'TotalReviewPending',
          'TotalReviewerAssignmentPending',
          'ReviewFailed',
          'InReviewMyAssignments',
          'ToDoTotal',
          'MandatoryTotal',
        ],
        optional: [
          'TotalUnresolvedCommentsCount',
          'MandatoryUnansweredTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
          'FollowupTotal',
        ],
      },
      rating_project: {
        main: [
          'TotalReviewPending',
          'TotalReviewerAssignmentPending',
          'ReviewFailed',
          'AutoFilledResponses',
          'InReviewMyAssignments',
          'WithTrackChangesCount',
        ],
        optional: [
          'TotalUnresolvedCommentsCount',
          'RatingReviewpendingCount',
          'RatingReviewFailed',
          'MyRatingReviewpendingCount',
          'RatingAssignmentpendingCount',
          'AssignedTotal',
          'ToDoTotal',
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'ValidationRequiredCount',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
          'FollowupTotal',
        ],
      },
      analyst_evaluation: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AutoFilledResponses',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
        ],
      },
      inbound: {
        main: [
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
          'FollowupTotal',
        ],
      },
    },
    manager: {
      dd_new: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_profile: {
        main: [
          'TotalReviewerAssignmentPending',
          'ReviewFailed',
          'InReviewMyAssignments',
          'WithTrackChangesCount',
          'AssignedTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'ToDoTotal',
          'MandatoryTotal',
          'TotalUnresolvedCommentsCount',
          'MandatoryUnansweredTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_ongoing: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_event_related: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'OpenFollowupTotal',
          'AutoFilledResponses',
          'ResolvedFollowupTotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
          'NATotal',
        ],
      },
      dd_internal: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'AutoFilledResponses',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
        ],
      },
      dd_doc: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'AutoFilledResponses',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
        ],
      },
      review_project_pre: {
        main: [
          'TotalReviewPending',
          'TotalReviewerAssignmentPending',
          'AutoFilledResponses',
          'ReviewFailed',
          'InReviewMyAssignments',
          'WithTrackChangesCount',
        ],
        optional: [
          'TotalUnresolvedCommentsCount',
          'AssignedTotal',
          'ToDoTotal',
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'AnsweredTotal',
          'ValidationRequiredCount',
          'UnAnsweredTotal',
          'NATotal',
          'FollowupTotal',
        ],
      },
      review_project_post: {
        main: [
          diligence.is_internal && 'TotalReviewPending',
          diligence.is_internal && 'TotalReviewerAssignmentPending',
          diligence.is_internal && 'InReviewMyAssignments',
          'AutoFilledResponses',
          'ToDoTotal',
          'MandatoryTotal',
        ],
        optional: [
          diligence.is_internal && 'TotalUnresolvedCommentsCount',
          'MandatoryUnansweredTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
          'FollowupTotal',
        ],
      },
      rating_project: {
        main: [
          'TotalReviewPending',
          'TotalReviewerAssignmentPending',
          'ReviewFailed',
          'InReviewMyAssignments',
          'WithTrackChangesCount',
        ],
        optional: [
          'TotalUnresolvedCommentsCount',
          'RatingReviewpendingCount',
          'RatingReviewFailed',
          'MyRatingReviewpendingCount',
          'RatingAssignmentpendingCount',
          'AssignedTotal',
          'ToDoTotal',
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          !diligence.completed_at && 'ValidationRequiredCount',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
        ],
      },
      analyst_evaluation: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
        ],
      },
      inbound: {
        main: [
          'AssignedTotal',
          'ToDoTotal',
          'AnsweredTotal',
          'UnAnsweredTotal',
          'NATotal',
          'OpenFollowupTotal',
          'ResolvedFollowupTotal',
          'AutoFilledResponses',
        ],
        optional: [
          'MandatoryTotal',
          'MandatoryUnansweredTotal',
          'ScoredTotal',
          'ExcludedFromRatingsCount',
          'FlaggedTotal',
          'FollowupTotal',
        ],
      },
    },
  };
};

export const defaultFilters = {
  main: [
    'AssignedTotal',
    'ToDoTotal',
    'AnsweredTotal',
    'UnAnsweredTotal',
    'NATotal',
  ],
  optional: ['MandatoryTotal', 'MandatoryUnansweredTotal'],
};

export const diligenceStatusConstant = {
  Completed: 'Completed',
  InReview: 'InReview',
  Evaluation: 'Evaluation',
  NotApproved: 'NotApproved',
  Approved: 'Approved',
  Deleted: 'Deleted',
  Retired: 'Retired',
  Withdrawn: 'Withdrawn',
  PendingRestart: 'PendingRestart',
  Started: 'Started',
  Followup: 'Followup',
  ExtensionRequested: 'ExtensionRequested',
  Scheduled: 'Scheduled',

  ReviewPassed: 'ReviewPassed',
  ReviewFailed: 'ReviewFailed',
};

export const trackChangeStatusConstant = {
  Started: 'Started',
  Accepted: 'Accepted',
  Rejected: 'Rejected',
  Pending: 'Pending', // custom def for local edit
};

export const diligenceTagMapper = {
  Completed: 'Completed',
  InReview: 'In Review',
  Evaluation: 'Evaluation',
  NotApproved: 'Not Approved',
  Approved: 'Approved',
  Deleted: 'Deleted',
  Retired: 'Retired',
  Withdrawn: 'Withdrawn',
  PendingRestart: 'Pending Restart',
  Started: 'Started',
  Followup: 'Follow up',
  ExtensionRequested: 'Extension Requested',
  ReviewPassed: 'Review Passed',
  ReviewFailed: 'Review Failed',
  Scheduled: 'Scheduled',
};
