export const EntityType = {
  Due_Diligence: 'duediligence',
  Note: 'note',
  Discussion: 'discussion',
  Invitation: 'invitation',
  To_Do: 'todo',
  Attachment: 'attachment',
  Response: 'response',
  Vehicle: 'vehicle',
  User: 'user',
  Fund: 'fund',
  Firm: 'firm',
  Template: 'template',
  Question: 'question',
  Review: 'review',
  Custom: 'custom',
  Track_Record: 'trackrecord',
  Form_ADV: 'formadv',
  ADV_Firm: 'advfirm',
  ADV_Private_Fund: 'advprivatefund',
  ADV_Service_Provider: 'advserviceprovider',
  Default: 'default',
  Report: 'report',
  Email: 'email',
  Workflow: 'workflow',
  Workflow_Step: 'workflow_step',
  Workflow_Action: 'workflow_action',
  Workflow_Action_Audit: 'workflow_action_audit',
  Section: 'section',
  Image: 'image',
  ADV_Flags: 'advflags',
  AUM_History: 'aumhistory',
  Meeting: 'meeting',
  Team: 'team',
  Workflow_Audit: 'workflow_audit',
  Rating: 'rating',
  Program: 'program',
  Master_Fund: 'masterfund',
  Strategy: 'strategy',
  Angular_Logger: 'angularlogger',
  Nested_Question: 'nestedquestion',
  Subsection: 'subsection',
  Issue: 'issue',
};

Object.freeze(EntityType);
