export const baseAuthenticatedRoute = 'app';

export const appRoutesNames = {
  LOGIN: 'login',
  PARTNERSHIP: 'partnership',
  FIRM_SETTING: 'firm/settings',
  MY_SETTING: 'settings',
  EXCEL_SYNC: 'excel_sync',
  REPORTS: 'reports',
  DILIGENCE: 'diligence',
  DILIGENCE_PROJECT: ':fromfirmId/firms/:tofirmId', // Project tabs routes
  DILIGENCE_PROJECT_GEN: 'projects/:diligenceId', // Generic route
  TEMPLATES: 'templates',
  DASH: 'dash',
  MONITOR: 'monitor',
  FIRMS: 'firms',
  FUNDS: 'funds',
  STRATEGY: 'strategies',
  VEHICLE: 'vehicles',
  FUNDS_MANAGER: 'funds/:fundId/profile/summary',
  FUNDS_INVESTOR: 'funds/:fundId/profile/monitor',
  CONTACTS: 'contacts/:Id',
  ANALYZE: 'analyze',
  ADVANCED_REPORTING: 'advanced_reporting',
  DOCUMENTS: 'documents',
  INVITE: 'invite',
  INVITE_MANAGER: 'newddq',
  TEMPLATE: 'template',
  ACTIVITY_INPROGRESS: 'projects/activity',
  CONTENT: 'content',
  RELEASES: 'releases',
  WORKFLOW_AUTOMATION: 'workflow_automation/:id',
  HOME: 'home',
  FORGOT_PASSWORD: 'begin_password_reset',
  CONFIRM_PASSWORD_RESET: 'confirm_password_reset',
  ACTIVATE: 'activate',
  TERMS_AND_CONDITIONS: 'terms-and-conditions',
  AI_TERMS_AND_CONDITIONS: 'ai-terms-of-use',
  MY_DOWNLOADS: 'my_downloads',
  PROFILE: 'settings',
  DATA_HUB: 'data_hub',
  RESOURCES: 'resources',
  FORMADV: 'form_adv',
  EXCELTOTEMPLATE: 'excel_to_template/:doc_id',
  WORDTOTEMPLATE: 'word_to_template/:doc_id',
  QUESTIONS: 'questions',
  WELCOME: 'welcome',
  WELCOME_TO_DV: 'welcome_to_dv',
  EUC: 'euc',
  HELP: 'help',
  FORMULA: 'formula',
  DOCUMENT: 'documents',
  DOCUMENT_DETAIL: 'document/:documentId/detail',
  MANAGE_AUM_TR: 'aum_tr',
  PLATFORM_ACTIVITY: 'platform_activity',
  INBOUND: 'inbound',
  SIGNUP: 'signup',
  PREMIUM: 'premium',
  TOEXTERNAL: 'to_external',
};
